version: "3.7"
name: crm
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: bash -c "if [ ! -d /home/frappe/frappe-bench ]; then bench init --skip-redis-config-generation frappe-bench --version develop && cd frappe-bench && bench get-app crm https://github.com/auliawinda12/crm --branch main && bench new-site crm.localhost --force --mariadb-root-password 123 --admin-password admin --no-mariadb-socket && bench --site crm.localhost install-app crm && bench --site crm.localhost set-config developer_mode 1 && bench --site crm.localhost set-config mute_emails 0 && bench --site crm.localhost set-config server_script_enabled 1 && bench --site crm.localhost clear-cache; fi; bench start"
    restart: unless-stopped
    environment:
      - SHELL=/bin/bash
    working_dir: /home/frappe
    volumes:
      - frappe-bench-data:/home/frappe/frappe-bench
    # - .:/workspace  # Temporarily disable
    ports:
      - 8000:8000
      - 9000:9000
    depends_on:
      - mariadb
      - redis

volumes:
  mariadb-data:
  frappe-bench-data:
